# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 037eeab27730120d9bcb5486cfb229425ed643b36bae2becdaa1461937886e4fa3a75074ecdd8be0835b86645604bfacf98a952ebd4f6fc07f53ed289f3ae0fe
  aws_access_key_id: aritomo
  aws_secret_access_key: Y2sB-^rtUbrV

test:
  secret_key_base: 0536609ab022d0671e3bfc47cfea01ca0019653efc90afda4ddd8a07cc82f3137a79a204d9f1512f6908f807a9289354884bf1c89105f792ca05dd41618a53ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: aritomo
  aws_secret_access_key: Y2sB-^rtUbrV


